---
- hosts: hosts
  become: yes
  remote_user: root
  tasks:

    - rpm_key:
        state: present
        key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
      when: ansible_os_family == "RedHat"

    - rpm_key:
        state: present
        key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
      when: ansible_os_family == "RedHat"
    
    - name: Add Rhel Repo
      yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/zabbix-release-6.0-1.el{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat"

    - name: Add Debian Repo
      get_url:
        url: https://repo.zabbix.com/zabbix/6.0/{{ ansible_distribution | lower }}/pool/main/z/zabbix-release/zabbix-release_6.0-1%2B{{ ansible_distribution | lower }}{{ansible_distribution_version}}_all.deb
        dest: "/tmp/zabbix-release_6.0-1%2B{{ ansible_distribution | lower }}{{ansible_distribution_version}}_all.deb"
      when: ansible_os_family == "Debian"

    - name: install zabbix deb in Debian
      apt: deb="/tmp/zabbix-release_6.0-1%2B{{ ansible_distribution | lower }}{{ansible_distribution_version}}_all.deb"
      when: ansible_os_family == "Debian"

    - name: Installing zabbix agent2
      yum:
        name:
          - zabbix-agent2
          - zabbix-sender
          - zabbix-get
        state: present
        update_cache: true
      when: ansible_os_family == "RedHat"

    - name: Installing zabbix agent2
      apt:
        name:
          - zabbix-agent2
          - zabbix-sender
          - zabbix-get
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Configure the Zabbix agent2
      replace:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '{{item.regexp}}'
        replace: '{{item.replace}}'
      with_items:
        - {regexp: "^Server=127.0.0.1$", replace: "Server={{zabbix_server}}"}
        - {regexp: "^ServerActive=127.0.0.1$", replace: "ServerActive={{zabbix_server}}"}
        - {regexp: "^Hostname=Zabbix server$", replace: "Hostname={{ansible_fqdn}}"}
      vars:
        - zabbix_server: zabbix.mono.biz.tr

    - name: Start the zabbix agent2
      service:
        name: zabbix-agent2
        enabled: yes
        state: started


